// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjrU1kiSHfahB8pHW6774VJ8Qom3P-_78',
    appId: '1:632918165657:web:5c00dd3b97e9abbd445008',
    messagingSenderId: '632918165657',
    projectId: 'koyambedu-6410a',
    authDomain: 'koyambedu-6410a.firebaseapp.com',
    storageBucket: 'koyambedu-6410a.appspot.com',
    measurementId: 'G-S5HYD3R34E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-c_xpdtAWAZvsgtJtrSLTBvlliuSCwjw',
    appId: '1:632918165657:android:a1663c2c9903d383445008',
    messagingSenderId: '632918165657',
    projectId: 'koyambedu-6410a',
    storageBucket: 'koyambedu-6410a.appspot.com',
  );
}
